"""Curated Tunis landmarks.  Each entry is matched against OSM by name regex
(French / Arabic / English variants) and, failing that, by proximity to the
fallback coordinate.  `kind` selects the bespoke generator in
web/src/landmarks.js; `params` are hints for that generator."""

CATALOG = [
    # --- Medina ---------------------------------------------------------------
    {"id": "zitouna", "name": "Mosquée Zitouna", "kind": "mosque",
     "match": r"zitouna|zaytuna|الزيتونة", "lonlat": (10.1712, 36.7975),
     "params": {"minaret": "square", "minaret_h": 43, "domes": "small", "courtyard": True}},
    {"id": "kasbah_mosque", "name": "Mosquée de la Kasbah", "kind": "mosque",
     "match": r"mosqu[ée]e? (de la )?kasbah|جامع القصبة", "lonlat": (10.1638, 36.7962),
     "params": {"minaret": "square", "minaret_h": 38}},
    {"id": "hammouda_pacha", "name": "Mosquée Hammouda Pacha", "kind": "mosque",
     "match": r"mosqu[ée]e? hammouda|hammouda pacha mosque|جامع حمودة", "lonlat": (10.1689, 36.7982),
     "params": {"minaret": "octagonal", "minaret_h": 30}},
    {"id": "youssef_dey", "name": "Mosquée Youssef Dey", "kind": "mosque",
     "match": r"youssef dey|yusuf dey|يوسف داي", "lonlat": (10.1660, 36.7968),
     "params": {"minaret": "octagonal", "minaret_h": 28}},
    {"id": "sidi_mahrez", "name": "Mosquée Sidi Mahrez", "kind": "mosque",
     "match": r"sidi mahrez|mahrez|سيدي محرز", "lonlat": (10.1701, 36.8027),
     "params": {"minaret": "octagonal", "minaret_h": 20, "domes": "ottoman"}},
    {"id": "bab_bhar", "name": "Bab el Bhar (Porte de France)", "kind": "gate",
     "match": r"bab (el |al |al-)?bhar|porte de france|باب البحر", "lonlat": (10.1746, 36.7995),
     "params": {"width": 12, "height": 12, "arch": 6, "heading": 90}},
    {"id": "bab_saadoun", "name": "Bab Saadoun", "kind": "gate",
     "match": r"bab sa+doun|باب سعدون", "lonlat": (10.1552, 36.8085),
     "params": {"width": 14, "height": 10, "arch": 4, "arches": 3, "heading": 35}},
    {"id": "bab_jedid", "name": "Bab Jedid", "kind": "gate",
     "match": r"bab (el )?j(e|a)did|باب الجديد", "lonlat": (10.1665, 36.7920),
     "params": {"width": 10, "height": 9, "arch": 4, "heading": 120}},
    {"id": "bab_khadra", "name": "Bab el Khadra", "kind": "gate",
     "match": r"bab (el |al )?khadra|باب الخضراء", "lonlat": (10.1672, 36.8082),
     "params": {"width": 12, "height": 9, "arch": 4, "arches": 3, "heading": 20}},
    {"id": "tourbet_bey", "name": "Tourbet el Bey", "kind": "mausoleum",
     "match": r"tourbet (el |al )?bey|تربة الباي", "lonlat": (10.1665, 36.7942),
     "params": {"domes": "green"}},
    {"id": "kasbah_monument", "name": "Place de la Kasbah", "kind": "obelisk",
     "match": r"monument (de la )?kasbah|place de la kasbah", "lonlat": (10.1620, 36.7975),
     "params": {"height": 30}},
    # --- Ville nouvelle ---------------------------------------------------------
    {"id": "cathedral", "name": "Cathédrale Saint-Vincent-de-Paul", "kind": "cathedral",
     "match": r"saint[- ]vincent|st\.? vincent|كاتدرائية", "lonlat": (10.1808, 36.8002),
     "params": {"height": 22, "towers": 2, "tower_h": 36, "dome": True, "facade": "S"}},
    {"id": "theatre", "name": "Théâtre municipal de Tunis", "kind": "civic",
     "match": r"th[ée][aâ]tre municipal|المسرح البلدي", "lonlat": (10.1806, 36.7994),
     "params": {"height": 18, "style": "artnouveau"}},
    {"id": "clock_tower", "name": "Horloge de la place du 14 Janvier", "kind": "clock_tower",
     "match": r"horloge|clock|ساعة|المنڨالة", "lonlat": (10.1866, 36.8006),
     "tags": {"man_made": "tower"}, "params": {"height": 38}},
    {"id": "hotel_lac", "name": "Hôtel du Lac", "kind": "inverted_pyramid",
     "match": r"h[oô]tel du lac|نزل البحيرة", "lonlat": (10.1893, 36.8016),
     "params": {"height": 40, "floors": 10}},
    {"id": "hotel_africa", "name": "Hôtel Africa", "kind": "tower",
     "match": r"h[oô]tel (l')?africa|el mouradi africa|hotel africa|أفريكا|أفريقا", "lonlat": (10.1830, 36.7994),
     "params": {"height": 70, "floors": 21, "style": "office", "colour": (0.42, 0.36, 0.31)}},
    {"id": "cite_culture", "name": "Cité de la Culture", "kind": "civic",
     "match": r"cit[ée] de la culture|مدينة الثقافة", "lonlat": (10.1780, 36.8085),
     "params": {"height": 22, "tower_h": 60, "dome": True}},
    {"id": "bardo", "name": "Musée national du Bardo", "kind": "palace",
     "match": r"mus[ée]e (national )?du bardo|bardo museum|متحف باردو", "lonlat": (10.1340, 36.8093),
     "params": {"height": 14, "domes": "small"}},
    {"id": "belvedere_koubba", "name": "Koubba du Belvédère", "kind": "koubba",
     "match": r"koubba|kobbet|قبة", "lonlat": (10.1738, 36.8245), "params": {}},
    # --- Carthage / coast -------------------------------------------------------
    {"id": "acropolium", "name": "Cathédrale Saint-Louis de Carthage (Acropolium)", "kind": "cathedral",
     "match": r"saint[- ]louis|acropolium|st\.? louis", "lonlat": (10.3232, 36.8528),
     "params": {"height": 16, "towers": 2, "tower_h": 30, "dome": True, "style": "byzantine", "facade": "W"}},
    {"id": "malik_ibn_anas", "name": "Mosquée Malik ibn Anas", "kind": "mosque",
     "match": r"malik (ibn|ben) anas|مالك بن أنس|el abidine|العابدين", "lonlat": (10.3196, 36.8560),
     "params": {"minaret": "square", "minaret_h": 65, "domes": "large"}},
    {"id": "antonine_baths", "name": "Thermes d'Antonin", "kind": "ruins",
     "match": r"thermes d.antonin|antonine baths|حمامات أنطوني", "lonlat": (10.3340, 36.8590),
     "params": {"height": 15}},
    {"id": "carthage_amphi", "name": "Amphithéâtre de Carthage", "kind": "amphitheatre",
     "match": r"amphith[ée][aâ]tre de carthage|carthage amphitheat", "lonlat": (10.3133, 36.8545),
     "params": {}},
    {"id": "carthage_theatre", "name": "Théâtre romain de Carthage", "kind": "amphitheatre",
     "match": r"th[ée][aâ]tre (romain|antique) de carthage|roman theat", "lonlat": (10.3283, 36.8572),
     "params": {}},
    {"id": "sbs_lighthouse", "name": "Phare de Sidi Bou Saïd", "kind": "lighthouse",
     "match": r"phare de sidi bou|sidi bou sa[iï]d lighthouse|منارة سيدي بوسعيد", "lonlat": (10.3480, 36.8724),
     "tags": {"man_made": "lighthouse"}, "params": {"height": 22}},
    {"id": "ennejma_ezzahra", "name": "Palais Ennejma Ezzahra", "kind": "palace",
     "match": r"ennejma ezzahra|nejma ezzahra|النجمة الزهراء", "lonlat": (10.3470, 36.8706),
     "params": {"height": 12}},
    {"id": "karraka", "name": "Fort de la Karraka", "kind": "fort",
     "match": r"karraka|قراقة|fort de la goulette", "lonlat": (10.3053, 36.8180),
     "params": {"height": 10}},
    {"id": "carthage_palace", "name": "Palais présidentiel de Carthage", "kind": "palace",
     "match": r"palais pr[ée]sidentiel|presidential palace|القصر الرئاسي", "lonlat": (10.3320, 36.8630),
     "params": {"height": 12}},
    {"id": "american_cemetery", "name": "Cimetière américain de Carthage", "kind": "memorial",
     "match": r"cimeti[èe]re am[ée]ricain|american cemetery", "lonlat": (10.3170, 36.8686),
     "params": {}},
    # --- South / west -----------------------------------------------------------
    {"id": "rades_stadium", "name": "Stade olympique Hammadi-Agrebi (Radès)", "kind": "stadium",
     "match": r"stade (olympique )?(de )?rad[eè]s|hammadi[- ]agrebi|الملعب الأولمبي", "lonlat": (10.2724, 36.7462),
     "params": {"height": 40}},
    {"id": "el_menzah_stadium", "name": "Stade olympique d'El Menzah", "kind": "stadium",
     "match": r"stade (olympique )?(d')?el menzah|ملعب المنزه", "lonlat": (10.1738, 36.8383),
     "params": {"height": 25}},
    {"id": "airport", "name": "Aéroport de Tunis-Carthage", "kind": "airport",
     "match": r"^a[ée]roport (international )?(de )?tunis|^tunis[- ]carthage (international )?airport|^مطار تونس",
     "lonlat": (10.2250, 36.8480), "prefer": "area", "params": {}},
]

# Ways/nodes with any of these tags become generic decorated features even when
# not in the catalog above.
GENERIC_KINDS = {
    "mosque": lambda t: t.get("building") == "mosque" or (
        t.get("amenity") == "place_of_worship" and t.get("religion") == "muslim"),
    "church": lambda t: t.get("building") in ("church", "cathedral", "chapel") or (
        t.get("amenity") == "place_of_worship" and t.get("religion") == "christian"),
    "synagogue": lambda t: t.get("building") == "synagogue" or (
        t.get("amenity") == "place_of_worship" and t.get("religion") == "jewish"),
    "minaret": lambda t: t.get("man_made") == "minaret",
    "tower": lambda t: t.get("man_made") in ("tower", "communications_tower", "water_tower", "lighthouse",
                                            "chimney", "mast", "obelisk"),
    "aqueduct": lambda t: t.get("historic") == "aqueduct" or t.get("bridge") == "aqueduct",
    "city_wall": lambda t: t.get("barrier") == "city_wall" or t.get("historic") == "city_wall",
    "fountain": lambda t: t.get("amenity") == "fountain",
    "stadium": lambda t: t.get("building") == "stadium" or t.get("leisure") == "stadium",
}
